interface=wlan3
driver=nl80211
ssid=testap
hw_mode=g
channel=1
auth_algs=1
interface=wlan3
driver=nl80211
ssid=testap
hw_mode=g
channel=1
auth_algs=1
interface=wlan3
driver=nl80211
ssid=testap
hw_mode=g
channel=1
auth_algs=1
